# Generated by Django 5.2 on 2025-04-12 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 12, 5, 36, 29, 299323, tzinfo=datetime.timezone.utc)),
        ),
    ]
